import { GridColDef } from "@mui/x-data-grid";

export const menu = [
  {
    id: 1,
    title: "main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "home.svg",
      },
      {
        id: 2,
        title: "Profile",
        url: "/users/1",
        icon: "user.svg",
      },
    ],
  },

  {
    id: 2,
    title: "lists",
    listItems: [
      {
        id: 1,
        title: "Users",
        url: "/users",
        icon: "user.svg",
      },
      {
        id: 2,
        title: "Products",
        url: "/products",
        icon: "product.svg",
      },
      {
        id: 3,
        title: "Orders",
        url: "/orders",
        icon: "order.svg",
      },
      {
        id: 4,
        title: "Posts",
        url: "/posts",
        icon: "post.svg",
      },
    ],
  },

  {
    id: 3,
    title: "general",
    listItems: [
      {
        id: 1,
        title: "Elements",
        url: "/",
        icon: "element.svg",
      },
      {
        id: 2,
        title: "Notes",
        url: "/",
        icon: "note.svg",
      },
      {
        id: 3,
        title: "Forms",
        url: "/",
        icon: "form.svg",
      },
      {
        id: 4,
        title: "Calendar",
        url: "/",
        icon: "calendar.svg",
      },
    ],
  },

  {
    id: 4,
    title: "maintenance",
    listItems: [
      {
        id: 1,
        title: "Settings",
        url: "/",
        icon: "setting.svg",
      },
      {
        id: 2,
        title: "Backups",
        url: "/",
        icon: "backup.svg",
      },
    ],
  },

  {
    id: 5,
    title: "analytics",
    listItems: [
      {
        id: 1,
        title: "Charts",
        url: "/",
        icon: "chart.svg",
      },
      {
        id: 2,
        title: "Logs",
        url: "/",
        icon: "log.svg",
      },
    ],
  },
];


export const topDealUsers = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Elva McDonald",
    email: "elva@gmail.com",
    amount: "3.668",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Linnie Nelson",
    email: "linnie@gmail.com",
    amount: "3.256",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Brent Reeves",
    email: "brent@gmail.com",
    amount: "2.998",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Adeline Watson",
    email: "adeline@gmail.com",
    amount: "2.512",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Juan Harrington",
    email: "juan@gmail.com",
    amount: "2.134",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Augusta McGee",
    email: "augusta@gmail.com",
    amount: "1.932",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Angel Thomas",
    email: "angel@gmail.com",
    amount: "1.560",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Sophia Turner",
    email: "sophia@gmail.com",
    amount: "1.432",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Michael Scott",
    email: "michael@gmail.com",
    amount: "1.278",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Emma Wilson",
    email: "emma@gmail.com",
    amount: "1.104",
  },
];


export const chartBoxUser = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title: "Total Users",
  number: "11.238",
  dataKey: "users",
  percentage: 45,

  chartData: [
    { name: "Sun", users: 400 },
    { name: "Mon", users: 600 },
    { name: "Tue", users: 500 },
    { name: "Wed", users: 700 },
    { name: "Thu", users: 400 },
    { name: "Fri", users: 500 },
    { name: "Sat", users: 450 },
  ],
};


export const barChartLeft = [
  { month: 'Jan', users: 4031 },
  { month: 'Feb', users: 3767 },
  { month: 'Mar', users: 2023 },
  { month: 'Apr', users: 2780 },
  { month: 'May', users: 1891 },
  { month: 'Jun', users: 2394 },
  { month: 'Jul', users: 2191 },
  { month: 'Aug', users: 3466 },
  { month: 'Sept', users: 8492 },
  { month: 'Oct', users: 4292 },
  { month: 'Nov', users: 6793 },
  { month: 'Dec', users: 3591 },

]

export const barChartRight = [
  { month: 'Jan', profit: 43314 },
  { month: 'Feb', profit: 13767 },
  { month: 'Mar', profit: 20233 },
  { month: 'Apr', profit: 27802 },
  { month: 'May', profit: 12891 },
  { month: 'Jun', profit: 52394 },
  { month: 'Jul', profit: 22191 },
  { month: 'Aug', profit: 34666 },
  { month: 'Sept', profit: 28492 },
  { month: 'Oct', profit: 24292 },
  { month: 'Nov', profit: 56793 },
  { month: 'Dec', profit: 43591 },
]





export const revenueChart = [
  {
    day: 'Mon',
    mobile: 4000,
    desktop: 2400,
    tablet: 1200,
  },
  {
    day: 'Tue',
    mobile: 3000,
    desktop: 9800,
    tablet: 1500,
  },
  {
    day: 'Wed',
    mobile: 2500,
    desktop: 4200,
    tablet: 1800,
  },
  {
    day: 'Thu',
    mobile: 3800,
    desktop: 3100,
    tablet: 2200,
  },
  {
    day: 'Fri',
    mobile: 4200,
    desktop: 2700,
    tablet: 2400,
  },
  {
    day: 'Sat',
    mobile: 5000,
    desktop: 3900,
    tablet: 2800,
  },
  {
    day: 'Sun',
    mobile: 3200,
    desktop: 2100,
    tablet: 1600,
  },
]
export const chartBoxRevenue = {
  color: "#36A2EB",
  icon: "/revenueIcon.svg",
  title: "Total Revenue",
  number: "$56.432",
  dataKey: "revenue",
  percentage: 12,

  chartData: [
    { name: "Sun", revenue: 3200 },
    { name: "Mon", revenue: 4100 },
    { name: "Tue", revenue: 3800 },
    { name: "Wed", revenue: 5200 },
    { name: "Thu", revenue: 4700 },
    { name: "Fri", revenue: 3900 },
    { name: "Sat", revenue: 3500 },
  ],
};

export const chartBoxProducts = {
  color: "#FFBB28",
  icon: "/productIcon.svg",
  title: "Total Products",
  number: "238",
  dataKey: "products",
  percentage: 21,

  chartData: [
    { name: "Sun", products: 120 },
    { name: "Mon", products: 180 },
    { name: "Tue", products: 160 },
    { name: "Wed", products: 220 },
    { name: "Thu", products: 190 },
    { name: "Fri", products: 240 },
    { name: "Sat", products: 210 },
  ],
};

export const chartBoxRatio = {
  color: "#82ca9d",
  icon: "/ratioIcon.svg",
  title: "Total Ratio",
  number: "2.6",
  dataKey: "ratio",
  percentage: -4,

  chartData: [
    { name: "Sun", ratio: 1.2 },
    { name: "Mon", ratio: 1.8 },
    { name: "Tue", ratio: 1.5 },
    { name: "Wed", ratio: 0.9 },
    { name: "Thu", ratio: 0.5 },
    { name: "Fri", ratio: 0.7 },
    { name: "Sat", ratio: 0.8 },
  ],
};


export const userRows = [
  {
  id: 1,
  img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Targaryen",
  firstName: "Daenerys",
  email: "daenerys@dragonstone.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 2,
  img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Snow",
  firstName: "Jon",
  email: "jon@winterfell.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 3,
  img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Lannister",
  firstName: "Jaime",
  email: "jaime@casterlyrock.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 4,
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Stark",
  firstName: "Arya",
  email: "arya@winterfell.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 5,
  img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Lannister",
  firstName: "Cersei",
  email: "cersei@casterlyrock.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 6,
  img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Baratheon",
  firstName: "Stannis",
  email: "stannis@dragonstone.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 7,
  img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Tyrell",
  firstName: "Margaery",
  email: "margaery@highgarden.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 8,
  img: "https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Martell",
  firstName: "Oberyn",
  email: "oberyn@dorne.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 9,
  img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Greyjoy",
  firstName: "Yara",
  email: "yara@pyke.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
 {
  id: 10,
  img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Stark",
  firstName: "Sansa",
  email: "sansa@winterfell.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 11,
  img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Stark",
  firstName: "Bran",
  email: "bran@winterfell.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 12,
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Stark",
  firstName: "Robb",
  email: "robb@winterfell.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 13,
  img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Snow",
  firstName: "Ygritte",
  email: "ygritte@wildlings.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 14,
  img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Targaryen",
  firstName: "Viserys",
  email: "viserys@dragonstone.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 15,
  img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Lannister",
  firstName: "Tyrion",
  email: "tyrion@casterlyrock.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 16,
  img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Baratheon",
  firstName: "Robert",
  email: "robert@kingslanding.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
{
  id: 17,
  img: "https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Greyjoy",
  firstName: "Theon",
  email: "theon@pyke.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 18,
  img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Mormont",
  firstName: "Jorah",
  email: "jorah@bearisland.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: true,
},
{
  id: 19,
  img: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1600",
  lastName: "Bolton",
  firstName: "Ramsay",
  email: "ramsay@dreadfort.com",
  phone: "123 456 789",
  createdAt: "01.02.2023",
  verified: false,
},
  ];
 export const productRows = [
{
  id: 1,
  img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg",
  title: "iPhone 15 Pro",
  color: "Titanium",
  producer: "Apple",
  price: "$999",
  createdAt: "01.02.2023",
  stock: 125,
},
{
  id: 2,
  img: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
  title: "Running Shoes",
  color: "Blue",
  producer: "Nike",
  price: "$120",
  createdAt: "02.02.2023",
  stock: 84,
},
{
  id: 3,
  img: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg",
  title: "Coffee Mug",
  color: "White",
  producer: "IKEA",
  price: "$15",
  createdAt: "03.02.2023",
  stock: 230,
},
{
  id: 4,
  img: "https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg",
  title: "Office Chair",
  color: "Black",
  producer: "Herman Miller",
  price: "$799",
  createdAt: "04.02.2023",
  stock: 12,
},
{
  id: 5,
  img: "https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg",
  title: "Backpack",
  color: "Gray",
  producer: "North Face",
  price: "$89",
  createdAt: "05.02.2023",
  stock: 56,
},
{
  id: 6,
  img: "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg",
  title: "Headphones",
  color: "Black",
  producer: "Sony",
  price: "$299",
  createdAt: "06.02.2023",
  stock: 41,
},
{
  id: 7,
  img: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg",
  title: "Camera",
  color: "Black",
  producer: "Canon",
  price: "$1199",
  createdAt: "07.02.2023",
  stock: 7,
},
{
  id: 8,
  img: "https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg",
  title: "Mountain Bike",
  color: "Red",
  producer: "Trek",
  price: "$1499",
  createdAt: "08.02.2023",
  stock: 18,
},
{
  id: 9,
  img: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg",
  title: "Desk Lamp",
  color: "White",
  producer: "Philips",
  price: "$45",
  createdAt: "09.02.2023",
  stock: 94,
},
{
  id: 10,
  img: "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg",
  title: "Wrist Watch",
  color: "Silver",
  producer: "Seiko",
  price: "$350",
  createdAt: "10.02.2023",
  stock: 23,
},
{
  id: 11,
  img: "https://images.pexels.com/photos/1667088/pexels-photo-1667088.jpeg",
  title: "Gaming Keyboard",
  color: "Black",
  producer: "Logitech",
  price: "$129",
  createdAt: "11.02.2023",
  stock: 67,
},
{
  id: 12,
  img: "https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg",
  title: "Gaming Mouse",
  color: "Black",
  producer: "Razer",
  price: "$79",
  createdAt: "12.02.2023",
  stock: 49,
},
{
  id: 13,
  img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg",
  title: "Galaxy S24",
  color: "Black",
  producer: "Samsung",
  price: "$899",
  createdAt: "13.02.2023",
  stock: 38,
},
{
  id: 14,
  img: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
  title: "MacBook Pro",
  color: "Space Gray",
  producer: "Apple",
  price: "$1999",
  createdAt: "14.02.2023",
  stock: 11,
},
{
  id: 15,
  img: "https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg",
  title: "Bluetooth Speaker",
  color: "Blue",
  producer: "JBL",
  price: "$149",
  createdAt: "15.02.2023",
  stock: 73,
},
{
  id: 16,
  img: "https://images.pexels.com/photos/821754/pexels-photo-821754.jpeg",
  title: "Sunglasses",
  color: "Black",
  producer: "Ray-Ban",
  price: "$199",
  createdAt: "16.02.2023",
  stock: 31,
},
{
  id: 17,
  img: "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg",
  title: "Tablet",
  color: "Silver",
  producer: "Apple",
  price: "$599",
  createdAt: "17.02.2023",
  stock: 27,
},
{
  id: 18,
  img: "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg",
  title: "Sneakers",
  color: "White",
  producer: "Adidas",
  price: "$110",
  createdAt: "18.02.2023",
  stock: 88,
},
{
  id: 19,
  img: "https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg",
  title: "Leather Wallet",
  color: "Brown",
  producer: "Fossil",
  price: "$65",
  createdAt: "19.02.2023",
  stock: 52,
},
{
  id: 20,
  img: "https://images.pexels.com/photos/5082566/pexels-photo-5082566.jpeg",
  title: "4K Monitor",
  color: "Black",
  producer: "LG",
  price: "$399",
  createdAt: "20.02.2023",
  stock: 16,
},]

export const singleUser = {
  id: 1,
  title: "John Doe",
  img: "https://images.pexels.com/photos/17397364/pexels-photo-17397364.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  info: {
    username: "Johndoe99",
    fullname: "John Doe",
    email: "johndoe@gmail.com",
    phone: "123 456 789",
    status: "verified",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "clicks", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        clicks: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        clicks: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        clicks: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        clicks: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        clicks: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        clicks: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        clicks: 4300,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "John Doe added 3 items into their wishlist",
      time: "1 week ago",
    },
    {
      text: "John Doe purchased Sony Bravia KD-32w800",
      time: "2 weeks ago",
    },
    {
      text: "John Doe reviewed a product",
      time: "1 month ago",
    },
    {
      text: "John Doe added 1 items into their wishlist",
      time: "1 month ago",
    },
    {
      text: "John Doe reviewed a product",
      time: "2 months ago",
    },
  ],
};
export const singleProduct = {
  id: 1,
  title: "Playstation 5 Digital Edition",
  img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
  info: {
    productId: "Ps5SDF1156d",
    color: "white",
    price: "$250.99",
    producer: "Sony",
    export: "Japan",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "orders", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        orders: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        orders: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        orders: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        orders: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        orders: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        orders: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        orders: 4300,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Mike Doe purchased Playstation 5 Digital Edition",
      time: "2 weeks ago",
    },
    {
      text: "Anna Doe reviewed the product",
      time: "1 month ago",
    },
    {
      text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Helen Doe reviewed the product",
      time: "2 months ago",
    },
  ],
};